### ISSUE TITLE
Download Webseite offline

### ISSUE THREAD

**Issue by Flinkpfote** [Panda-Projects/CloudNet-V3-Webinterface#4]
Die Download Webseite ist offline

**Comment by tunikakeks** [comment]
Immernoch down
wget https://files.panda-studios.eu/2/0.3/cloudnet-rest.jar

--2023-07-05 11:21:26--  https://files.panda-studios.eu/2/0.3/cloudnet-rest.jar
Resolving files.panda-studios.eu (files.panda-studios.eu)... failed:
Name or service not known.
wget: unable to resolve host address ‘files.panda-studios.eu’
